/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform API
 * Part of the OpenAPI specification for the PlanQK Platform.
 *
 * The version of the OpenAPI document: v1
 * Contact: info@anaqor.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSubscriptionRequest,
  ServiceExecutionConsumerDto,
  SubscriptionDto,
} from '../models/index';
import {
    CreateSubscriptionRequestFromJSON,
    CreateSubscriptionRequestToJSON,
    ServiceExecutionConsumerDtoFromJSON,
    ServiceExecutionConsumerDtoToJSON,
    SubscriptionDtoFromJSON,
    SubscriptionDtoToJSON,
} from '../models/index';

export interface CreateSubscriptionOperationRequest {
    createSubscriptionRequest: CreateSubscriptionRequest;
    xOrganizationId?: string;
}

export interface DeleteSubscriptionRequest {
    id: string;
    xOrganizationId?: string;
}

export interface GetSubscriptionRequest {
    id: string;
    xOrganizationId?: string;
}

export interface GetSubscriptionServiceExecutionsRequest {
    id: string;
    xOrganizationId?: string;
}

/**
 * 
 */
export class ServicePlatformSubscriptionsApi extends runtime.BaseAPI {

    /**
     * Creates a subscription to an internally or publicly published service. To subscribe a service, you must only supply the id of the service and the application.
     */
    async createSubscriptionRaw(requestParameters: CreateSubscriptionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionDto>> {
        if (requestParameters.createSubscriptionRequest === null || requestParameters.createSubscriptionRequest === undefined) {
            throw new runtime.RequiredError('createSubscriptionRequest','Required parameter requestParameters.createSubscriptionRequest was null or undefined when calling createSubscription.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xOrganizationId !== undefined && requestParameters.xOrganizationId !== null) {
            headerParameters['X-OrganizationId'] = String(requestParameters.xOrganizationId);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Auth-Token"] = await this.configuration.apiKey("X-Auth-Token"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/subscriptions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSubscriptionRequestToJSON(requestParameters.createSubscriptionRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionDtoFromJSON(jsonValue));
    }

    /**
     * Creates a subscription to an internally or publicly published service. To subscribe a service, you must only supply the id of the service and the application.
     */
    async createSubscription(requestParameters: CreateSubscriptionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionDto> {
        const response = await this.createSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes a specific subscription.
     */
    async deleteSubscriptionRaw(requestParameters: DeleteSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteSubscription.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xOrganizationId !== undefined && requestParameters.xOrganizationId !== null) {
            headerParameters['X-OrganizationId'] = String(requestParameters.xOrganizationId);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Auth-Token"] = await this.configuration.apiKey("X-Auth-Token"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/subscriptions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes a specific subscription.
     */
    async deleteSubscription(requestParameters: DeleteSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSubscriptionRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a specific subscription.
     */
    async getSubscriptionRaw(requestParameters: GetSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getSubscription.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xOrganizationId !== undefined && requestParameters.xOrganizationId !== null) {
            headerParameters['X-OrganizationId'] = String(requestParameters.xOrganizationId);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Auth-Token"] = await this.configuration.apiKey("X-Auth-Token"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/subscriptions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionDtoFromJSON(jsonValue));
    }

    /**
     * Retrieves a specific subscription.
     */
    async getSubscription(requestParameters: GetSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionDto> {
        const response = await this.getSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the service executions of a subscription.
     */
    async getSubscriptionServiceExecutionsRaw(requestParameters: GetSubscriptionServiceExecutionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ServiceExecutionConsumerDto>>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getSubscriptionServiceExecutions.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xOrganizationId !== undefined && requestParameters.xOrganizationId !== null) {
            headerParameters['X-OrganizationId'] = String(requestParameters.xOrganizationId);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Auth-Token"] = await this.configuration.apiKey("X-Auth-Token"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        const response = await this.request({
            path: `/subscriptions/{id}/service-executions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceExecutionConsumerDtoFromJSON));
    }

    /**
     * Retrieves the service executions of a subscription.
     */
    async getSubscriptionServiceExecutions(requestParameters: GetSubscriptionServiceExecutionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ServiceExecutionConsumerDto>> {
        const response = await this.getSubscriptionServiceExecutionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
