export const randomName = (): string => {
  const suffix = Math.random().toString(36).slice(2, 7)

  const randomAdjective = adjectives[Math.floor(Math.random() * adjectives.length)]
  const randomAnimal = animals[Math.floor(Math.random() * animals.length)]

  return `${randomAdjective}-${randomAnimal}-${suffix}`
}

const adjectives = [
  'admiring',
  'adoring',
  'blissful',
  'brave',
  'calm',
  'charming',
  'cozy',
  'dazzling',
  'delightful',
  'eager',
  'fierce',
  'fluffy',
  'gloomy',
  'graceful',
  'jolly',
  'lively',
  'misty',
  'peaceful',
  'radiant',
  'silly',
]

const animals = [
  'aardvark',
  'alpaca',
  'antelope',
  'baboon',
  'bat',
  'beaver',
  'buffalo',
  'camel',
  'cheetah',
  'chimpanzee',
  'cobra',
  'cougar',
  'coyote',
  'crocodile',
  'dingo',
  'dolphin',
  'elephant',
  'elk',
  'ferret',
  'gazelle',
  'giraffe',
  'gorilla',
  'grizzly bear',
  'hippopotamus',
  'hyena',
  'jaguar',
  'kangaroo',
  'koala',
  'leopard',
  'lion',
  'llama',
  'lynx',
  'marmot',
  'moose',
  'orangutan',
  'otter',
  'panda',
  'panther',
  'puma',
  'rabbit',
  'raccoon',
  'rhinoceros',
  'seal',
  'shark',
  'skunk',
  'sloth',
  'tapir',
  'tiger',
  'walrus',
  'wombat',
  'zebra',
]
