/**
 * PlanQK Platform OpenAPI definition
 * OpenAPI definition for the Platform and Ecosystem for Quantum-assisted Artificial Intelligence Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: info@stoneone.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TaxonomyElement } from './taxonomyElement';

export class ApiOverviewDto {
    'id'?: string;
    'serviceId'?: string;
    'name'?: string;
    'provider'?: string;
    'type'?: ApiOverviewDto.TypeEnum;
    'quantumBackend'?: ApiOverviewDto.QuantumBackendEnum;
    'lifecycle'?: ApiOverviewDto.LifecycleEnum;
    'industries'?: Set<TaxonomyElement>;
    'pricingCategory'?: ApiOverviewDto.PricingCategoryEnum;
    'rating'?: number;
    'logoUrl'?: string;
    'isFeatured'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "serviceId",
            "baseName": "serviceId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ApiOverviewDto.TypeEnum"
        },
        {
            "name": "quantumBackend",
            "baseName": "quantumBackend",
            "type": "ApiOverviewDto.QuantumBackendEnum"
        },
        {
            "name": "lifecycle",
            "baseName": "lifecycle",
            "type": "ApiOverviewDto.LifecycleEnum"
        },
        {
            "name": "industries",
            "baseName": "industries",
            "type": "Set<TaxonomyElement>"
        },
        {
            "name": "pricingCategory",
            "baseName": "pricingCategory",
            "type": "ApiOverviewDto.PricingCategoryEnum"
        },
        {
            "name": "rating",
            "baseName": "rating",
            "type": "number"
        },
        {
            "name": "logoUrl",
            "baseName": "logoUrl",
            "type": "string"
        },
        {
            "name": "isFeatured",
            "baseName": "isFeatured",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ApiOverviewDto.attributeTypeMap;
    }
}

export namespace ApiOverviewDto {
    export enum TypeEnum {
        Managed = <any> 'MANAGED',
        External = <any> 'EXTERNAL'
    }
    export enum QuantumBackendEnum {
        Ibm = <any> 'IBM',
        Ionq = <any> 'IONQ',
        Dwave = <any> 'DWAVE',
        None = <any> 'NONE'
    }
    export enum LifecycleEnum {
        Error = <any> 'ERROR',
        Creating = <any> 'CREATING',
        Created = <any> 'CREATED',
        Accessible = <any> 'ACCESSIBLE',
        Published = <any> 'PUBLISHED'
    }
    export enum PricingCategoryEnum {
        Free = <any> 'FREE',
        Freemium = <any> 'FREEMIUM',
        Commercial = <any> 'COMMERCIAL'
    }
}
