/**
 * PlanQK Platform OpenAPI definition
 * OpenAPI definition for the Platform and Ecosystem for Quantum-assisted Artificial Intelligence Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: info@stoneone.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ApplicationDto {
    /**
    * The access permission role for this entity of the current user
    */
    'currentUserPermission'?: ApplicationDto.CurrentUserPermissionEnum;
    'id'?: string;
    'name'?: string;
    'subscriptionCount'?: number;
    'createdAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currentUserPermission",
            "baseName": "currentUserPermission",
            "type": "ApplicationDto.CurrentUserPermissionEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "subscriptionCount",
            "baseName": "subscriptionCount",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApplicationDto.attributeTypeMap;
    }
}

export namespace ApplicationDto {
    export enum CurrentUserPermissionEnum {
        Viewer = <any> 'VIEWER',
        Maintainer = <any> 'MAINTAINER',
        Owner = <any> 'OWNER'
    }
}
