/**
 * PlanQK Platform OpenAPI definition
 * OpenAPI definition for the Platform and Ecosystem for Quantum-assisted Artificial Intelligence Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: info@stoneone.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ValidationResult } from './validationResult';

export class BuildJobDto {
    'status'?: BuildJobDto.StatusEnum;
    'step'?: BuildJobDto.StepEnum;
    'createdAt'?: string;
    'finishedAt'?: string;
    'validationResult'?: ValidationResult;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "BuildJobDto.StatusEnum"
        },
        {
            "name": "step",
            "baseName": "step",
            "type": "BuildJobDto.StepEnum"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "finishedAt",
            "baseName": "finishedAt",
            "type": "string"
        },
        {
            "name": "validationResult",
            "baseName": "validationResult",
            "type": "ValidationResult"
        }    ];

    static getAttributeTypeMap() {
        return BuildJobDto.attributeTypeMap;
    }
}

export namespace BuildJobDto {
    export enum StatusEnum {
        StatusUnknown = <any> 'STATUS_UNKNOWN',
        Pending = <any> 'PENDING',
        Queued = <any> 'QUEUED',
        Working = <any> 'WORKING',
        Success = <any> 'SUCCESS',
        Failure = <any> 'FAILURE',
        InternalError = <any> 'INTERNAL_ERROR',
        Timeout = <any> 'TIMEOUT',
        Cancelled = <any> 'CANCELLED',
        Expired = <any> 'EXPIRED',
        Unrecognized = <any> 'UNRECOGNIZED'
    }
    export enum StepEnum {
        BuildImage = <any> 'BUILD_IMAGE',
        PushImage = <any> 'PUSH_IMAGE',
        DeployService = <any> 'DEPLOY_SERVICE',
        Unknown = <any> 'UNKNOWN'
    }
}
