/**
 * PlanQK Platform OpenAPI definition
 * OpenAPI definition for the Platform and Ecosystem for Quantum-assisted Artificial Intelligence Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: info@stoneone.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateProductRequest } from './createProductRequest';

export class CreateExternalServicePricingPlanRequest {
    'type': CreateExternalServicePricingPlanRequest.TypeEnum;
    'products'?: Array<CreateProductRequest>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CreateExternalServicePricingPlanRequest.TypeEnum"
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<CreateProductRequest>"
        }    ];

    static getAttributeTypeMap() {
        return CreateExternalServicePricingPlanRequest.attributeTypeMap;
    }
}

export namespace CreateExternalServicePricingPlanRequest {
    export enum TypeEnum {
        Free = <any> 'FREE',
        Commercial = <any> 'COMMERCIAL'
    }
}
