/**
 * PlanQK Platform OpenAPI definition
 * OpenAPI definition for the Platform and Ecosystem for Quantum-assisted Artificial Intelligence Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: info@stoneone.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DataPoolRef {
    'dataPoolId'?: string;
    'dataSourceDescriptorId'?: string;
    'fileId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dataPoolId",
            "baseName": "dataPoolId",
            "type": "string"
        },
        {
            "name": "dataSourceDescriptorId",
            "baseName": "dataSourceDescriptorId",
            "type": "string"
        },
        {
            "name": "fileId",
            "baseName": "fileId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataPoolRef.attributeTypeMap;
    }
}

