/**
 * PlanQK Platform OpenAPI definition
 * OpenAPI definition for the Platform and Ecosystem for Quantum-assisted Artificial Intelligence Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: info@stoneone.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ResourceConfiguration } from './resourceConfiguration';

export class GpuConfiguration extends ResourceConfiguration {
    'amount'?: number;
    'accelerator'?: GpuConfiguration.AcceleratorEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "accelerator",
            "baseName": "accelerator",
            "type": "GpuConfiguration.AcceleratorEnum"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(GpuConfiguration.attributeTypeMap);
    }
}

export namespace GpuConfiguration {
    export enum AcceleratorEnum {
        NvidiaTeslaT4 = <any> 'NVIDIA_TESLA_T4',
        NvidiaTeslaV100 = <any> 'NVIDIA_TESLA_V100',
        NvidiaTeslaA100 = <any> 'NVIDIA_TESLA_A100',
        NvidiaTeslaP100 = <any> 'NVIDIA_TESLA_P100',
        None = <any> 'NONE'
    }
}
