/**
 * PlanQK Platform OpenAPI definition
 * OpenAPI definition for the Platform and Ecosystem for Quantum-assisted Artificial Intelligence Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: info@stoneone.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiDto } from './apiDto';
import { ApplicationDto } from './applicationDto';
import { PricingPlanDto } from './pricingPlanDto';

export class SubscriptionDto {
    'id'?: string;
    'application'?: ApplicationDto;
    'api'?: ApiDto;
    'pricingPlan'?: PricingPlanDto;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "application",
            "baseName": "application",
            "type": "ApplicationDto"
        },
        {
            "name": "api",
            "baseName": "api",
            "type": "ApiDto"
        },
        {
            "name": "pricingPlan",
            "baseName": "pricingPlan",
            "type": "PricingPlanDto"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionDto.attributeTypeMap;
    }
}

