/**
 * PlanQK Platform OpenAPI definition
 * OpenAPI definition for the Platform and Ecosystem for Quantum-assisted Artificial Intelligence Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: info@stoneone.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ValidationResult {
    'state'?: ValidationResult.StateEnum;
    'summary'?: string;
    'messages'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "state",
            "baseName": "state",
            "type": "ValidationResult.StateEnum"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ValidationResult.attributeTypeMap;
    }
}

export namespace ValidationResult {
    export enum StateEnum {
        Success = <any> 'SUCCESS',
        Warning = <any> 'WARNING',
        Error = <any> 'ERROR'
    }
}
