/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform OpenAPI definition
 * OpenAPI definition for the Platform and Ecosystem for Quantum-assisted Artificial Intelligence Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: info@stoneone.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime'

/**
 *
 * @export
 * @interface CpuConfigurationAllOf
 */
export interface CpuConfigurationAllOf {
    /**
     *
     * @type {number}
     * @memberof CpuConfigurationAllOf
     */
    amount?: number;
    /**
     *
     * @type {string}
     * @memberof CpuConfigurationAllOf
     */
    unit?: string;
}

/**
 * Check if a given object implements the CpuConfigurationAllOf interface.
 */
export function instanceOfCpuConfigurationAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CpuConfigurationAllOfFromJSON(json: any): CpuConfigurationAllOf {
    return CpuConfigurationAllOfFromJSONTyped(json, false);
}

export function CpuConfigurationAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CpuConfigurationAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
    };
}

export function CpuConfigurationAllOfToJSON(value?: CpuConfigurationAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'amount': value.amount,
        'unit': value.unit,
    };
}

