/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform API
 * Part of the OpenAPI specification for the PlanQK Platform.
 *
 * The version of the OpenAPI document: v1
 * Contact: info@anaqor.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateDataPoolRequest
 */
export interface CreateDataPoolRequest {
    /**
     *
     * @type {string}
     * @memberof CreateDataPoolRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateDataPoolRequest interface.
 */
export function instanceOfCreateDataPoolRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateDataPoolRequestFromJSON(json: any): CreateDataPoolRequest {
    return CreateDataPoolRequestFromJSONTyped(json, false);
}

export function CreateDataPoolRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDataPoolRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'name': json['name'],
    };
}

export function CreateDataPoolRequestToJSON(value?: CreateDataPoolRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'name': value.name,
    };
}

