/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform API
 * Part of the OpenAPI specification for the PlanQK Platform.
 *
 * The version of the OpenAPI document: v1
 * Contact: info@anaqor.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateSubscriptionRequest
 */
export interface CreateSubscriptionRequest {
    /**
     *
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    serviceId: string;
    /**
     *
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    applicationId: string;
}

/**
 * Check if a given object implements the CreateSubscriptionRequest interface.
 */
export function instanceOfCreateSubscriptionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "serviceId" in value;
    isInstance = isInstance && "applicationId" in value;

    return isInstance;
}

export function CreateSubscriptionRequestFromJSON(json: any): CreateSubscriptionRequest {
    return CreateSubscriptionRequestFromJSONTyped(json, false);
}

export function CreateSubscriptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscriptionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'serviceId': json['serviceId'],
        'applicationId': json['applicationId'],
    };
}

export function CreateSubscriptionRequestToJSON(value?: CreateSubscriptionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'serviceId': value.serviceId,
        'applicationId': value.applicationId,
    };
}

