/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform API
 * Part of the OpenAPI specification for the PlanQK Platform.
 *
 * The version of the OpenAPI document: v1
 * Contact: info@anaqor.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime'

/**
 *
 * @export
 * @interface CreateWorkflowServiceRequest
 */
export interface CreateWorkflowServiceRequest {
    /**
     *
     * @type {string}
     * @memberof CreateWorkflowServiceRequest
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof CreateWorkflowServiceRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateWorkflowServiceRequest interface.
 */
export function instanceOfCreateWorkflowServiceRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateWorkflowServiceRequestFromJSON(json: any): CreateWorkflowServiceRequest {
    return CreateWorkflowServiceRequestFromJSONTyped(json, false);
}

export function CreateWorkflowServiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkflowServiceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function CreateWorkflowServiceRequestToJSON(value?: CreateWorkflowServiceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'name': value.name,
        'description': value.description,
    };
}

