/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform OpenAPI definition
 * OpenAPI definition for the Platform and Ecosystem for Quantum-assisted Artificial Intelligence Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: info@stoneone.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime'

/**
 *
 * @export
 * @interface CreateSubscriptionRequest
 */
export interface CreateSubscriptionRequest {
    /**
     *
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    applicationId?: string;
    /**
     *
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    pricingPlanId?: string;
}

/**
 * Check if a given object implements the CreateSubscriptionRequest interface.
 */
export function instanceOfCreateSubscriptionRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateSubscriptionRequestFromJSON(json: any): CreateSubscriptionRequest {
    return CreateSubscriptionRequestFromJSONTyped(json, false);
}

export function CreateSubscriptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscriptionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'applicationId': !exists(json, 'applicationId') ? undefined : json['applicationId'],
        'pricingPlanId': !exists(json, 'pricingPlanId') ? undefined : json['pricingPlanId'],
    };
}

export function CreateSubscriptionRequestToJSON(value?: CreateSubscriptionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'applicationId': value.applicationId,
        'pricingPlanId': value.pricingPlanId,
    };
}

