/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform API
 * Part of the OpenAPI specification for the PlanQK Platform.
 *
 * The version of the OpenAPI document: v1
 * Contact: info@anaqor.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime'
import type {ResourceConfiguration} from './ResourceConfiguration'
import {ResourceConfigurationFromJSONTyped, ResourceConfigurationToJSON} from './ResourceConfiguration'

/**
 *
 * @export
 * @interface GpuConfiguration
 */
export interface GpuConfiguration extends ResourceConfiguration {
    /**
     *
     * @type {number}
     * @memberof GpuConfiguration
     */
    amount?: number;
    /**
     *
     * @type {string}
     * @memberof GpuConfiguration
     */
    accelerator?: GpuConfigurationAcceleratorEnum;
}


/**
 * @export
 */
export const GpuConfigurationAcceleratorEnum = {
    NvidiaTeslaT4: 'NVIDIA_TESLA_T4',
    NvidiaTeslaV100: 'NVIDIA_TESLA_V100',
    NvidiaTeslaA100: 'NVIDIA_TESLA_A100',
    NvidiaTeslaP100: 'NVIDIA_TESLA_P100',
    None: 'NONE'
} as const;
export type GpuConfigurationAcceleratorEnum = typeof GpuConfigurationAcceleratorEnum[keyof typeof GpuConfigurationAcceleratorEnum];


/**
 * Check if a given object implements the GpuConfiguration interface.
 */
export function instanceOfGpuConfiguration(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GpuConfigurationFromJSON(json: any): GpuConfiguration {
    return GpuConfigurationFromJSONTyped(json, false);
}

export function GpuConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GpuConfiguration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ResourceConfigurationFromJSONTyped(json, ignoreDiscriminator),
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'accelerator': !exists(json, 'accelerator') ? undefined : json['accelerator'],
    };
}

export function GpuConfigurationToJSON(value?: GpuConfiguration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ResourceConfigurationToJSON(value),
        'amount': value.amount,
        'accelerator': value.accelerator,
    };
}

