/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform OpenAPI definition
 * OpenAPI definition for the Platform and Ecosystem for Quantum-assisted Artificial Intelligence Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: info@stoneone.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime'

/**
 *
 * @export
 * @interface MemoryConfigurationAllOf
 */
export interface MemoryConfigurationAllOf {
  /**
   *
   * @type {number}
   * @memberof MemoryConfigurationAllOf
   */
  amount?: number;
  /**
   *
   * @type {string}
   * @memberof MemoryConfigurationAllOf
   */
  unit?: string;
}

/**
 * Check if a given object implements the MemoryConfigurationAllOf interface.
 */
export function instanceOfMemoryConfigurationAllOf(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function MemoryConfigurationAllOfFromJSON(json: any): MemoryConfigurationAllOf {
  return MemoryConfigurationAllOfFromJSONTyped(json, false)
}

export function MemoryConfigurationAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryConfigurationAllOf {
  if ((json === undefined) || (json === null)) {
    return json
  }
  return {

    'amount': !exists(json, 'amount') ? undefined : json['amount'],
    'unit': !exists(json, 'unit') ? undefined : json['unit'],
  }
}

export function MemoryConfigurationAllOfToJSON(value?: MemoryConfigurationAllOf | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {

    'amount': value.amount,
    'unit': value.unit,
  }
}

