/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform API
 * Part of the OpenAPI specification for the PlanQK Platform.
 *
 * The version of the OpenAPI document: v1
 * Contact: info@anaqor.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime'
import type {ResourceConfiguration} from './ResourceConfiguration'
import {ResourceConfigurationFromJSONTyped, ResourceConfigurationToJSON} from './ResourceConfiguration'

/**
 *
 * @export
 * @interface MemoryConfiguration
 */
export interface MemoryConfiguration extends ResourceConfiguration {
    /**
     *
     * @type {number}
     * @memberof MemoryConfiguration
     */
    amount?: number;
    /**
     *
     * @type {string}
     * @memberof MemoryConfiguration
     */
    unit?: string;
}

/**
 * Check if a given object implements the MemoryConfiguration interface.
 */
export function instanceOfMemoryConfiguration(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MemoryConfigurationFromJSON(json: any): MemoryConfiguration {
    return MemoryConfigurationFromJSONTyped(json, false);
}

export function MemoryConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryConfiguration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ResourceConfigurationFromJSONTyped(json, ignoreDiscriminator),
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
    };
}

export function MemoryConfigurationToJSON(value?: MemoryConfiguration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ResourceConfigurationToJSON(value),
        'amount': value.amount,
        'unit': value.unit,
    };
}

