/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform API
 * Part of the OpenAPI specification for the PlanQK Platform.
 *
 * The version of the OpenAPI document: v1
 * Contact: info@anaqor.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime'
import type {DataPoolDto} from './DataPoolDto'
import {DataPoolDtoFromJSON, DataPoolDtoToJSON} from './DataPoolDto'
import type {PageableObject} from './PageableObject'
import {PageableObjectFromJSON, PageableObjectToJSON} from './PageableObject'
import type {SortObject} from './SortObject'
import {SortObjectFromJSON, SortObjectToJSON} from './SortObject'

/**
 *
 * @export
 * @interface PageDataPoolDto
 */
export interface PageDataPoolDto {
    /**
     *
     * @type {number}
     * @memberof PageDataPoolDto
     */
    totalPages?: number;
    /**
     *
     * @type {number}
     * @memberof PageDataPoolDto
     */
    totalElements?: number;
    /**
     *
     * @type {boolean}
     * @memberof PageDataPoolDto
     */
    first?: boolean;
    /**
     *
     * @type {number}
     * @memberof PageDataPoolDto
     */
    size?: number;
    /**
     *
     * @type {Array<DataPoolDto>}
     * @memberof PageDataPoolDto
     */
    content?: Array<DataPoolDto>;
    /**
     *
     * @type {number}
     * @memberof PageDataPoolDto
     */
    number?: number;
    /**
     *
     * @type {SortObject}
     * @memberof PageDataPoolDto
     */
    sort?: SortObject;
    /**
     *
     * @type {number}
     * @memberof PageDataPoolDto
     */
    numberOfElements?: number;
    /**
     *
     * @type {PageableObject}
     * @memberof PageDataPoolDto
     */
    pageable?: PageableObject;
    /**
     *
     * @type {boolean}
     * @memberof PageDataPoolDto
     */
    last?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PageDataPoolDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageDataPoolDto interface.
 */
export function instanceOfPageDataPoolDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PageDataPoolDtoFromJSON(json: any): PageDataPoolDto {
    return PageDataPoolDtoFromJSONTyped(json, false);
}

export function PageDataPoolDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageDataPoolDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'totalElements': !exists(json, 'totalElements') ? undefined : json['totalElements'],
        'first': !exists(json, 'first') ? undefined : json['first'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'content': !exists(json, 'content') ? undefined : ((json['content'] as Array<any>).map(DataPoolDtoFromJSON)),
        'number': !exists(json, 'number') ? undefined : json['number'],
        'sort': !exists(json, 'sort') ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': !exists(json, 'numberOfElements') ? undefined : json['numberOfElements'],
        'pageable': !exists(json, 'pageable') ? undefined : PageableObjectFromJSON(json['pageable']),
        'last': !exists(json, 'last') ? undefined : json['last'],
        'empty': !exists(json, 'empty') ? undefined : json['empty'],
    };
}

export function PageDataPoolDtoToJSON(value?: PageDataPoolDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'totalPages': value.totalPages,
        'totalElements': value.totalElements,
        'first': value.first,
        'size': value.size,
        'content': value.content === undefined ? undefined : ((value.content as Array<any>).map(DataPoolDtoToJSON)),
        'number': value.number,
        'sort': SortObjectToJSON(value.sort),
        'numberOfElements': value.numberOfElements,
        'pageable': PageableObjectToJSON(value.pageable),
        'last': value.last,
        'empty': value.empty,
    };
}

