/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform API
 * Part of the OpenAPI specification for the PlanQK Platform.
 *
 * The version of the OpenAPI document: v1
 * Contact: info@anaqor.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime'

/**
 *
 * @export
 * @interface ProductUsageDto
 */
export interface ProductUsageDto {
    /**
     *
     * @type {string}
     * @memberof ProductUsageDto
     */
    timestamp?: string;
    /**
     *
     * @type {string}
     * @memberof ProductUsageDto
     */
    productName?: string;
    /**
     *
     * @type {string}
     * @memberof ProductUsageDto
     */
    productId?: string;
    /**
     *
     * @type {number}
     * @memberof ProductUsageDto
     */
    unitPrice?: number;
    /**
     *
     * @type {string}
     * @memberof ProductUsageDto
     */
    currency?: string;
    /**
     *
     * @type {number}
     * @memberof ProductUsageDto
     */
    count?: number;
}

/**
 * Check if a given object implements the ProductUsageDto interface.
 */
export function instanceOfProductUsageDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductUsageDtoFromJSON(json: any): ProductUsageDto {
    return ProductUsageDtoFromJSONTyped(json, false);
}

export function ProductUsageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductUsageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'productName': !exists(json, 'productName') ? undefined : json['productName'],
        'productId': !exists(json, 'productId') ? undefined : json['productId'],
        'unitPrice': !exists(json, 'unitPrice') ? undefined : json['unitPrice'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function ProductUsageDtoToJSON(value?: ProductUsageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'timestamp': value.timestamp,
        'productName': value.productName,
        'productId': value.productId,
        'unitPrice': value.unitPrice,
        'currency': value.currency,
        'count': value.count,
    };
}

