/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform API
 * Part of the OpenAPI specification for the PlanQK Platform.
 *
 * The version of the OpenAPI document: v1
 * Contact: info@anaqor.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime'

/**
 *
 * @export
 * @interface ServiceExecutionDto
 */
export interface ServiceExecutionDto {
    /**
     *
     * @type {string}
     * @memberof ServiceExecutionDto
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof ServiceExecutionDto
     */
    createdAt?: string;
    /**
     *
     * @type {string}
     * @memberof ServiceExecutionDto
     */
    startedAt?: string;
    /**
     *
     * @type {string}
     * @memberof ServiceExecutionDto
     */
    endedAt?: string;
}

/**
 * Check if a given object implements the ServiceExecutionDto interface.
 */
export function instanceOfServiceExecutionDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ServiceExecutionDtoFromJSON(json: any): ServiceExecutionDto {
    return ServiceExecutionDtoFromJSONTyped(json, false);
}

export function ServiceExecutionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceExecutionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'startedAt': !exists(json, 'startedAt') ? undefined : json['startedAt'],
        'endedAt': !exists(json, 'endedAt') ? undefined : json['endedAt'],
    };
}

export function ServiceExecutionDtoToJSON(value?: ServiceExecutionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'createdAt': value.createdAt,
        'startedAt': value.startedAt,
        'endedAt': value.endedAt,
    };
}

