/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform API
 * Part of the OpenAPI specification for the PlanQK Platform.
 *
 * The version of the OpenAPI document: v1
 * Contact: info@anaqor.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {CpuConfiguration} from './CpuConfiguration'
import {CpuConfigurationFromJSONTyped, CpuConfigurationToJSON, instanceOfCpuConfiguration} from './CpuConfiguration'
import type {GpuConfiguration} from './GpuConfiguration'
import {GpuConfigurationFromJSONTyped, GpuConfigurationToJSON, instanceOfGpuConfiguration} from './GpuConfiguration'
import type {MemoryConfiguration} from './MemoryConfiguration'
import {
  instanceOfMemoryConfiguration,
  MemoryConfigurationFromJSONTyped,
  MemoryConfigurationToJSON,
} from './MemoryConfiguration'

/**
 * @type UpdateResourceConfigurationRequest
 *
 * @export
 */
export type UpdateResourceConfigurationRequest = CpuConfiguration | GpuConfiguration | MemoryConfiguration;

export function UpdateResourceConfigurationRequestFromJSON(json: any): UpdateResourceConfigurationRequest {
    return UpdateResourceConfigurationRequestFromJSONTyped(json, false);
}

export function UpdateResourceConfigurationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateResourceConfigurationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...CpuConfigurationFromJSONTyped(json, true), ...GpuConfigurationFromJSONTyped(json, true), ...MemoryConfigurationFromJSONTyped(json, true) };
}

export function UpdateResourceConfigurationRequestToJSON(value?: UpdateResourceConfigurationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfCpuConfiguration(value)) {
        return CpuConfigurationToJSON(value as CpuConfiguration);
    }
    if (instanceOfGpuConfiguration(value)) {
        return GpuConfigurationToJSON(value as GpuConfiguration);
    }
    if (instanceOfMemoryConfiguration(value)) {
        return MemoryConfigurationToJSON(value as MemoryConfiguration);
    }

    return {};
}

