/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform OpenAPI definition
 * OpenAPI definition for the Platform and Ecosystem for Quantum-assisted Artificial Intelligence Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: info@stoneone.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  CpuConfiguration,
  CpuConfigurationFromJSONTyped,
  CpuConfigurationToJSON,
  instanceOfCpuConfiguration,
} from './CpuConfiguration'
import {
  GpuConfiguration,
  GpuConfigurationFromJSONTyped,
  GpuConfigurationToJSON,
  instanceOfGpuConfiguration,
} from './GpuConfiguration'
import {
  instanceOfMemoryConfiguration,
  MemoryConfiguration,
  MemoryConfigurationFromJSONTyped,
  MemoryConfigurationToJSON,
} from './MemoryConfiguration'
import {
  instanceOfPlatformManagedConfiguration,
  PlatformManagedConfiguration,
  PlatformManagedConfigurationFromJSONTyped,
  PlatformManagedConfigurationToJSON,
} from './PlatformManagedConfiguration'

/**
 * @type UpdateResourceConfigurationRequest
 *
 * @export
 */
export type UpdateResourceConfigurationRequest = CpuConfiguration | GpuConfiguration | MemoryConfiguration | PlatformManagedConfiguration;

export function UpdateResourceConfigurationRequestFromJSON(json: any): UpdateResourceConfigurationRequest {
    return UpdateResourceConfigurationRequestFromJSONTyped(json, false);
}

export function UpdateResourceConfigurationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateResourceConfigurationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...CpuConfigurationFromJSONTyped(json, true), ...GpuConfigurationFromJSONTyped(json, true), ...MemoryConfigurationFromJSONTyped(json, true), ...PlatformManagedConfigurationFromJSONTyped(json, true) };
}

export function UpdateResourceConfigurationRequestToJSON(value?: UpdateResourceConfigurationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfCpuConfiguration(value)) {
        return CpuConfigurationToJSON(value as CpuConfiguration);
    }
    if (instanceOfGpuConfiguration(value)) {
        return GpuConfigurationToJSON(value as GpuConfiguration);
    }
    if (instanceOfMemoryConfiguration(value)) {
        return MemoryConfigurationToJSON(value as MemoryConfiguration);
    }
    if (instanceOfPlatformManagedConfiguration(value)) {
        return PlatformManagedConfigurationToJSON(value as PlatformManagedConfiguration);
    }

    return {};
}

