/* tslint:disable */
/* eslint-disable */
/**
 * PlanQK Platform API
 * Part of the OpenAPI specification for the PlanQK Platform.
 *
 * The version of the OpenAPI document: v1
 * Contact: info@anaqor.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime'
import type {ServiceDefinitionDtoSource} from './ServiceDefinitionDtoSource'
import {ServiceDefinitionDtoSourceFromJSON, ServiceDefinitionDtoSourceToJSON} from './ServiceDefinitionDtoSource'

/**
 *
 * @export
 * @interface UpdateVersionRequest
 */
export interface UpdateVersionRequest {
    /**
     *
     * @type {string}
     * @memberof UpdateVersionRequest
     */
    description?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof UpdateVersionRequest
     */
    industryUuids?: Array<string>;
    /**
     *
     * @type {ServiceDefinitionDtoSource}
     * @memberof UpdateVersionRequest
     */
    source?: ServiceDefinitionDtoSource;
}

/**
 * Check if a given object implements the UpdateVersionRequest interface.
 */
export function instanceOfUpdateVersionRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateVersionRequestFromJSON(json: any): UpdateVersionRequest {
    return UpdateVersionRequestFromJSONTyped(json, false);
}

export function UpdateVersionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateVersionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'description': !exists(json, 'description') ? undefined : json['description'],
        'industryUuids': !exists(json, 'industryUuids') ? undefined : json['industryUuids'],
        'source': !exists(json, 'source') ? undefined : ServiceDefinitionDtoSourceFromJSON(json['source']),
    };
}

export function UpdateVersionRequestToJSON(value?: UpdateVersionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'description': value.description,
        'industryUuids': value.industryUuids,
        'source': ServiceDefinitionDtoSourceToJSON(value.source),
    };
}

